[project]
name = "econ-project"
r_version = "4.5"

repositories = [
  { alias = "CRAN", url = "https://cran.r-project.org/" },
  { alias = "BioCsoft", url = "https://bioconductor.org/packages/3.22/bioc", force_source = true },
  { alias = "BioCann", url = "https://bioconductor.org/packages/3.22/data/annotation", force_source = true },
  { alias = "BioCexp", url = "https://bioconductor.org/packages/3.22/data/experiment", force_source = true },
  { alias = "BioCworkflows", url = "https://bioconductor.org/packages/3.22/workflows", force_source = true },
  { alias = "RForge", url = "https://R-Forge.R-project.org", force_source = true },
]

dependencies = [
  "AER",
  "car",
  "fixest",
  "forecast",
  "ivreg",
  "lmtest",
  "marginaleffects",
  "plm",
  "sandwich",
  "tseries",
  "urca",
  "zoo",
  "alpaca",
  "aod",
  "apollo",
  "apt",
  "bacondecomp",
  "bayesm",
  "betareg",
  "bife",
  "bimets",
  "BMA",
  "BMS",
  "boot",
  "bootstrap",
  "brglm",
  "CADFtest",
  "censReg",
  "clubSandwich",
  "clusterSEs",
  "collapse",
  "crch",
  "decompr",
  "did",
  "did2s",
  "dlsem",
  "DoubleML",
  "DRDID",
  "dynlm",
  "Ecdat",
  "effects",
  "erer",
  "estimatr",
  "etwfe",
  "expsmooth",
  "ExtremeBounds",
  "feisr",
  "fma",
  "frontier",
  "fxregime",
  "gam",
  "gamlss",
  "geepack",
  "gets",
  "glmx",
  "gmm",
  "gmnl",
  "gravity",
  "grf",
  "gsynth",
  "gvc",
  "hdm",
  "Hmisc",
  "ineq",
  "lavaan",
  "lfe",
  "LinRegInteractive",
  "lme4",
  "logitr",
  "lpirfs",
  "margins",
  "MASS",
  "Matrix",
  "Mcomp",
  "meboot",
  "mfx",
  "mgcv",
  "mhurdle",
  "micEcon",
  "micEconAids",
  "micEconCES",
  "micEconSNQP",
  "midasr",
  "mixl",
  "mlogit",
  "MNP",
  "modelsummary",
  "multiwayvcov",
  "nanoparquet",
  "nlme",
  "nnet",
  "NNS",
  "nonnest2",
  "np",
  "nse",
  "ordinal",
  "OrthoPanels",
  "panelvar",
  "pcse",
  "pder",
  "pdR",
  "pdynmc",
  "penppml",
  "pglm",
  "pscl",
  "psidR",
  "pvars",
  "pwt",
  "pwt8",
  "pwt9",
  "quantreg",
  "RATest",
  "Rchoice",
  "rddensity",
  "rdlocrand",
  "rdmulti",
  "rdpower",
  "rdrobust",
  "reldist",
  "REndo",
  "rms",
  "RprobitB",
  "sampleSelection",
  "segmented",
  "sem",
  "semsfa",
  "simpleboot",
  "SparseM",
  "spatialprobit",
  "spatialreg",
  "sphet",
  "splm",
  "spsur",
  "ssfa",
  "ssmrob",
  "sstvars",
  "SteinIV",
  "strucchange",
  "survival",
  "Synth",
  "systemfit",
  "tidysynth",
  "truncreg",
  "tsDyn",
  "vars",
  "VGAM",
  "wbstats",
  "wINEQ",
  "wooldridge",
  "xts",
  "zTree",
  "sf",
  "terra",
  "gstat",
  "spatstat",
  "dplyr",
  "ggplot2",
  "data.table",
  "mlr3",
  "caret",
  "glmnet",
  "randomForest",
  "broom",
  "mrIML",
  "Silhouette",
  "survdnn",
  "GCEstim",
  "gilmour",
  "hbsaems",
  "clarabel",
  "condor",
  "GPUmatrix",
  "hydroMOPSO",
  "dataverifyr",
  "neotoma2",
  "rpaleoclim",
  "janitor",
  "skimr",
  "lubridate",
  "naniar",
  "leaflet",
  "knitr",
  "DT",
  "shiny",
  "rsample",
  "parsnip",
  "recipes",
  "multcomp",
  "vcd",
  "gvcAnalyzer",
  "gctsc",
  "ciflyr",
  "hmde",
  "ironseed",
  "RBaM",
  "ArgentinAPI",
  "datacommons",
  "imfweo",
  "pubchem.bio",
  "redlist",
  "mapgl",
  "mapdeck",
  "ggspatial",
  "maptiles",
  "classInt",
  "DCluster",
  "deldir",
  "dggridR",
  "geoR",
  "stars",
  "ade4",
  "blockCV",
  "CARBayes",
  "metaplus",
  "BayesMultMeta",
  "xmeta",
  "CBnetworkMA",
  "rstan",
  "BLPestimatoR",
  "sitrep",
  "epitabulate",
  "epidict",
  "epikit",
  "apyramid",
  "cifmodeling",
  "APS",
  "bayesRecon",
  "biogeom",
  "blatent",
  "BREADR",
  "carsAlgo",
  "chiOpenData",
  "CohortContrast",
  "countrycode",
  "devtools",
  "emBALVI",
  "engression",
  "fairmetrics",
  "geneticae",
  "ggseg",
  "gleam",
  "glm4",
  "GWnorm",
  "hlmLab",
  "leidenAlg",
  "linreg",
  "llm.api",
  "miniCRAN",
  "motmot",
  "mrf",
  "MultiSpline",
  "TSMCP",
  "vaccinationimpact",
  "whatifbandit",
  "admisc",
  "asteRisk",
  "dsb",
  "echoice2",
  "EGM",
  "listenv",
  "SeasEpi",
  "spinner",
  "SynthETIC",
  "torch",
  "factorH",
  "factorplot",
  "GPTCM",
  "karyotapR",
  "PopComm",
  "PortfolioTesteR",
  "promises",
  "sc2sc",
  "amsSim",
  "bayesCureRateModel",
  "bibliorefer",
  "DataVisualizations",
  "dynConfiR",
  "EEEA",
  "MKMeans",
  "moveEZ",
  "MuChPoint",
  "multilevel",
  "MVTests",
  "mxnorm",
  "pdcor",
  "predRupdate",
  "pwSEM",
  "qmd",
  "qpdf",
  "giscoR",
  "elevatr",
  "geodata",
  "osmdata",
  "chirps",
  "eurostat",
  "riem",
  "rnaturalearth",
  "spocc",
  "openair",
  "rinat",
  "tigris",
  "tidycensus",
  "leafpop",
  "leafem",
  "leafsync",
  "ranger",
  "spgwr",
  "GWmodel",
  "palmerpenguins",
  "igraph",
  "numDeriv",
  "bookdown",
  "DBI",
  "DiagrammeR",
  "Formula",
  "S7",
  "base64enc",
  "bit",
  "bit64",
  "blob",
  "cellranger",
  "checkmate",
  "clipr",
  "cpp11",
  "furrr",
  "future",
  "foreach",
  "IRkernel",
  "tidyverse",
  "MatchIt",
  "cobalt",
  "tidymodels",
  "fable",
  "prophet",
  "rvest",
  "languageserver",
  "LearnBayes",
  "rpart",
  "Rcpp",
  "RcppEigen",
  "R6",
  "RColorBrewer",
  "askpass",
  "backports",
  "bayestestR",
  "brew",
  "brio",
  "bslib",
  "cachem",
  "callr",
  "cli",
  "codetools",
  "colorspace",
  "commonmark",
  "crayon",
  "credentials",
  "curl",
  "datawizard",
  "desc",
  "diffobj",
  "digest",
  "downlit",
  "ellipsis",
  "evaluate",
  "fansi",
  "farver",
  "fastmap",
  "fontawesome",
  "fs",
  "generics",
  "gert",
  "gh",
  "gitcreds",
  "glue",
  "gtable",
  "here",
  "highr",
  "htmltools",
  "htmlwidgets",
  "httpuv",
  "httr",
  "httr2",
  "ini",
  "insight",
  "isoband",
  "iterators",
  "jquerylib",
  "jsonlite",
  "kableExtra",
  "labeling",
  "later",
  "lattice",
  "lifecycle",
  "magrittr",
  "memoise",
  "mime",
  "miniUI",
  "munsell",
  "openssl",
  "parameters",
  "performance",
  "pillar",
  "pkgbuild",
  "pkgconfig",
  "pkgdown",
  "pkgload",
  "praise",
  "prettyunits",
  "processx",
  "profvis",
  "ps",
  "purrr",
  "ragg",
  "rappdirs",
  "rcmdcheck",
  "remotes",
  "renv",
  "rlang",
  "rmarkdown",
  "roxygen2",
  "rprojroot",
  "rstudioapi",
  "rversions",
  "sass",
  "scales",
  "sessioninfo",
  "sourcetools",
  "stringi",
  "stringr",
  "svglite",
  "sys",
  "systemfonts",
  "tables",
  "testthat",
  "textshaping",
  "tibble",
  "tidyselect",
  "tinytex",
  "urlchecker",
  "usethis",
  "utf8",
  "vctrs",
  "viridisLite",
  "waldo",
  "whisker",
  "withr",
  "xfun",
  "xml2",
  "xopen",
  "xtable",
  "yaml",
  "zip",
]
