#!/bin/bash
# Generate IDE MCP configurations from the launch environment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
export PROJECT_ROOT
MODE="write"

for arg in "$@"; do
  case "$arg" in
    --check) MODE="check" ;;
    --print) MODE="print" ;;
    --write) MODE="write" ;;
  esac
done

build_json() {
  python3 - <<'PYJSON'
import json
import os
import shutil
import shlex
from collections import OrderedDict

project_root = os.environ["PROJECT_ROOT"]
with open(f"{project_root}/docs/ai/config-templates/mcp.example.json", encoding="utf-8") as handle:
    servers = OrderedDict(json.load(handle)["mcpServers"])
if os.environ.get("ENABLE_GOOGLE_DRIVE_MCP") == "1" and os.path.exists(
    f"{project_root}/secrets/credentials.json"
):
    servers["google-drive"] = {
        "command": "bash",
        "args": [
            "-lc",
            f"cd {shlex.quote(project_root + '/secrets')} && exec mcp-server-gdrive",
        ],
        "description": "Google Drive integration - search, read, and view drive files",
    }
if os.environ.get("BRAVE_API_KEY"):
    servers["brave-search"] = {
        "command": "mcp-server-brave-search",
        "args": [],
    }
if os.environ.get("EXA_API_KEY"):
    servers["exa"] = {
        "command": "npx",
        "args": ["--no-install", "exa-mcp-server"],
    }
if os.environ.get("GITHUB_PERSONAL_ACCESS_TOKEN"):
    servers["github"] = {
        "command": "npx",
        "args": ["--no-install", "@modelcontextprotocol/server-github"],
    }
if os.environ.get("DATABASE_URL"):
    servers["postgres"] = {
        "command": "bash",
        "args": ["-c", 'exec mcp-server-postgres "${DATABASE_URL:?Set DATABASE_URL in the IDE environment}"'],
    }
if os.environ.get("ENABLE_CONTEXT_MCP") == "1":
    if shutil.which("codebase-memory-mcp"):
        servers["codebase-memory-mcp"] = {"command": "codebase-memory-mcp", "args": []}
    if shutil.which("token-optimizer-mcp"):
        servers["token-optimizer-mcp"] = {
            "command": "token-optimizer-mcp",
            "args": [],
        }

print(json.dumps({"mcpServers": servers}, indent=2))
PYJSON
}

build_template_json() {
  GENERATED_MCP_JSON="$MCP_JSON" python3 - <<'PYJSON'
import json
import os

payload = json.loads(os.environ["GENERATED_MCP_JSON"])
with open(os.environ["PROJECT_ROOT"] + "/docs/ai/config-templates/claude-mcp.example.json", encoding="utf-8") as handle:
    definition = json.load(handle)
payload = {**definition, **payload}
print(json.dumps(payload, indent=2))
PYJSON
}

build_codex_toml() {
  GENERATED_MCP_JSON="$MCP_JSON" python3 - <<'PYTOML'
import json
import os

servers = json.loads(os.environ["GENERATED_MCP_JSON"])["mcpServers"]
with open(os.environ["PROJECT_ROOT"] + "/docs/ai/config-templates/codex.example.toml", encoding="utf-8") as handle:
    definition = handle.read().strip()
lines = ["# Generated by scripts/setup_ide_mcp.sh.", definition, ""]
environment = {
    "brave-search": "BRAVE_API_KEY",
    "exa": "EXA_API_KEY",
    "github": "GITHUB_PERSONAL_ACCESS_TOKEN",
    "postgres": "DATABASE_URL",
}
for name, server in servers.items():
    lines.append(f"[mcp_servers.{name}]")
    if "command" in server:
        lines.append(f"command = {json.dumps(server['command'])}")
    if "args" in server:
        args = ", ".join(json.dumps(arg) for arg in server["args"])
        lines.append(f"args = [{args}]")
    if "url" in server:
        lines.append(f"url = {json.dumps(server['url'])}")
    if name in environment:
        lines.append(f"env_vars = [{json.dumps(environment[name])}]")
    lines.append("")
print("\n".join(lines))
PYTOML
}

sync_json_mcp_key() {
  local full_path="$1"
  GENERATED_MCP_JSON="$MCP_JSON" TARGET_JSON="$full_path" MODE="$MODE" python3 - <<'PYSYNC'
import json
import os
import sys
from pathlib import Path

path = Path(os.environ["TARGET_JSON"])
expected = json.loads(os.environ["GENERATED_MCP_JSON"])["mcpServers"]
mode = os.environ["MODE"]
if not path.exists():
    print(f"Configuration file missing: {path}")
    sys.exit(1)
with path.open(encoding="utf-8") as handle:
    data = json.load(handle)
actual = data.get("mcpServers")
if mode == "check":
    if actual != expected:
        print(f"Configuration differs: mcpServers in {path}")
        sys.exit(1)
else:
    data["mcpServers"] = expected
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"Synced mcpServers in {path}")
PYSYNC
}

sync_devcontainer_mcp_keys() {
  local full_path="$1"
  GENERATED_MCP_JSON="$MCP_JSON" TARGET_JSON="$full_path" MODE="$MODE" python3 - <<'PYSYNC'
import json
import os
import sys
from pathlib import Path

path = Path(os.environ["TARGET_JSON"])
expected = json.loads(os.environ["GENERATED_MCP_JSON"])["mcpServers"]
mode = os.environ["MODE"]
with path.open(encoding="utf-8") as handle:
    data = json.load(handle)
changed = False
state_path = Path(os.environ["PROJECT_ROOT"]) / ".agents/state/mcp-generated.json"
state = json.loads(state_path.read_text()) if state_path.exists() else {}
for name, customization in data.get("customizations", {}).items():
    settings = customization.get("settings") if isinstance(customization, dict) else None
    if isinstance(settings, dict) and "mcpServers" in settings:
        key = str(path.relative_to(os.environ["PROJECT_ROOT"])) + "#" + name
        managed = set(state.get(key, []))
        user_owned = {n: value for n, value in settings["mcpServers"].items() if n not in managed}
        generated_servers = {n: value for n, value in expected.items() if n not in user_owned}
        merged = {**user_owned, **generated_servers}
        if settings["mcpServers"] != merged:
            if mode == "check":
                print(f"Configuration differs: customization mcpServers in {path}")
                sys.exit(1)
            settings["mcpServers"] = merged
            changed = True
        if mode != "check":
            state[key] = sorted(generated_servers)
if mode != "check" and changed:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"Synced customization mcpServers in {path}")
if mode != "check":
    state_path.parent.mkdir(parents=True, exist_ok=True)
    state_path.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
PYSYNC
}

MCP_JSON="$(build_json)"
TEMPLATE_JSON="$(build_template_json)"
CODEX_TOML="$(build_codex_toml)"

if [ "$MODE" = "print" ]; then
  printf '%s\n' "$MCP_JSON"
  exit 0
fi

process_file() {
  local full_path="$1"
  local content="$2"
  GENERATED_CONFIG="$content" TARGET_JSON="$full_path" MODE="$MODE" python3 - <<'PYSYNC'
import json
import os
import sys
from pathlib import Path

path = Path(os.environ["TARGET_JSON"])
generated = json.loads(os.environ["GENERATED_CONFIG"])
data = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
expected = dict(data)
state_path = Path(os.environ["PROJECT_ROOT"]) / ".agents/state/mcp-generated.json"
state = json.loads(state_path.read_text()) if state_path.exists() else {}
key = str(path.relative_to(os.environ["PROJECT_ROOT"]))
managed = set(state.get(key, []))
actual = data.get("mcpServers", {})
user_owned = {name: value for name, value in actual.items() if name not in managed}
generated_servers = {name: value for name, value in generated["mcpServers"].items() if name not in user_owned}
expected["mcpServers"] = {**user_owned, **generated_servers}
if "__TEMPLATE_WARNING__" in generated:
    expected["__TEMPLATE_WARNING__"] = generated["__TEMPLATE_WARNING__"]
if os.environ["MODE"] == "check":
    if data != expected:
        print(f"Configuration differs: generated MCP fields in {path}")
        sys.exit(1)
else:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(expected, indent=2) + "\n", encoding="utf-8")
    state[key] = sorted(generated_servers)
    state_path.parent.mkdir(parents=True, exist_ok=True)
    state_path.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")
    print(f"Synced generated MCP fields in {path}")
PYSYNC
}

sync_codex_mcp() {
  local full_path="$1"
  GENERATED_TOML="$CODEX_TOML" TARGET_TOML="$full_path" MODE="$MODE" python3 - <<'PYSYNC'
import os
from pathlib import Path
import re
import sys

path = Path(os.environ["TARGET_TOML"])
original = path.read_text(encoding="utf-8") if path.exists() else ""
start = "# BEGIN generated MCP: scripts/setup_ide_mcp.sh"
end = "# END generated MCP: scripts/setup_ide_mcp.sh"
generated = os.environ["GENERATED_TOML"].removeprefix("# Generated by scripts/setup_ide_mcp.sh.\n").strip()
if original.count(start) != original.count(end) or original.count(start) > 1:
    raise ValueError("Malformed generated MCP markers")
manual = original
if start in original:
    manual = original[:original.index(start)] + original[original.index(end) + len(end):]
manual_names = set(re.findall(r"^\s*\[mcp_servers\.([^\].]+)(?:\.[^\]]+)?\]", manual, re.MULTILINE))
if original.startswith("# Generated by scripts/setup_ide_mcp.sh."):
    manual_names = set()
kept_generated = []
skip = False
for line in generated.splitlines():
    header = re.match(r"^\s*\[mcp_servers\.([^\]]+)\]", line)
    if header:
        skip = header.group(1) in manual_names
    if not skip:
        kept_generated.append(line)
generated = "\n".join(kept_generated).strip()
block = start + "\n" + generated + ("\n" if generated else "") + end + "\n"
if start in original:
    a, b = original.index(start), original.index(end)
    if b < a:
        raise ValueError("Malformed generated MCP markers")
    finish = b + len(end)
    if original[finish:finish+1] == "\n":
        finish += 1
    expected = original[:a] + block + original[finish:]
else:
    # Migrate only a configuration explicitly labelled by the earlier generator.
    # Unlabelled, manually configured MCP tables remain user-owned.
    kept = []
    in_generated_table = False
    legacy = original.startswith("# Generated by scripts/setup_ide_mcp.sh.")
    for line in original.splitlines(keepends=True):
        header = re.match(r"^\s*\[([^\]]+)\]", line)
        if header:
            in_generated_table = legacy and header.group(1).startswith("mcp_servers.")
        if not in_generated_table and not (legacy and line.startswith("# Generated by scripts/setup_ide_mcp.sh.")):
            kept.append(line)
    base = "".join(kept)
    expected = base + ("" if not base or base.endswith("\n\n") else "\n" if base.endswith("\n") else "\n\n") + block
if os.environ["MODE"] == "check":
    if expected != original:
        print(f"Configuration differs: generated MCP block in {path}")
        sys.exit(1)
else:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"Synced generated MCP block in {path}")
PYSYNC
}

active_files=(
  "$PROJECT_ROOT/.cursor/mcp.json"
  "$PROJECT_ROOT/.vscode/cline_mcp_settings.json"
  "$PROJECT_ROOT/.vscode/roo_cline_mcp_settings.json"
  "$PROJECT_ROOT/.windsurf/mcp.json"
  "$PROJECT_ROOT/.gemini/mcp.json"
  "$PROJECT_ROOT/.gemini/mcp-configs/mcp-servers.json"
  "$PROJECT_ROOT/.mcp.json"
  "$PROJECT_ROOT/mcp.json"
  "$PROJECT_ROOT/.agents/mcp.json"
)

for target in "${active_files[@]}"; do
  process_file "$target" "$MCP_JSON"
done

process_file "$PROJECT_ROOT/.claude/mcp-configs/mcp-servers.json" "$TEMPLATE_JSON"
sync_codex_mcp "$PROJECT_ROOT/.codex/config.toml"
process_file "$PROJECT_ROOT/.vscode/settings.json" "$MCP_JSON"
sync_devcontainer_mcp_keys "$PROJECT_ROOT/.devcontainer/devcontainer.json"

if [ "$MODE" = "check" ]; then
  echo "MCP configurations match the launch environment."
else
  echo "Generated MCP configurations."
fi
