#!/bin/bash
# Automatically sets up MCP configuration for all IDEs from one generated source.

set -euo pipefail

PROJECT_ROOT="/workspaces/econ-project"
MODE="write"

for arg in "$@"; do
  case "$arg" in
    --check) MODE="check" ;;
    --print) MODE="print" ;;
    --write) MODE="write" ;;
  esac
done

build_json() {
  python3 - <<'PYJSON'
import json
import os
import shutil
from collections import OrderedDict

project_root = "/workspaces/econ-project"
servers = OrderedDict()
if os.environ.get("ENABLE_GOOGLE_DRIVE_MCP") == "1" and os.path.exists(
    f"{project_root}/secrets/credentials.json"
):
    servers["google-drive"] = {
        "command": "bash",
        "args": [
            "-lc",
            f"cd {project_root}/secrets && mcp-server-gdrive",
        ],
        "description": "Google Drive integration - search, read, and view drive files",
    }
if os.environ.get("BRAVE_API_KEY"):
    servers["brave-search"] = {
        "command": "mcp-server-brave-search",
        "args": [],
        "env": {"BRAVE_API_KEY": "env:BRAVE_API_KEY"},
    }
if os.environ.get("EXA_API_KEY"):
    servers["exa"] = {
        "command": "npx",
        "args": ["--no-install", "exa-mcp-server"],
        "env": {"EXA_API_KEY": "env:EXA_API_KEY"},
    }
if os.environ.get("GITHUB_PERSONAL_ACCESS_TOKEN"):
    servers["github"] = {
        "command": "npx",
        "args": ["--no-install", "@modelcontextprotocol/server-github"],
        "env": {"GITHUB_PERSONAL_ACCESS_TOKEN": "env:GITHUB_PERSONAL_ACCESS_TOKEN"},
    }
if os.environ.get("DATABASE_URL"):
    servers["postgres"] = {
        "command": "mcp-server-postgres",
        "args": [os.environ["DATABASE_URL"]],
    }
if os.environ.get("ENABLE_CONTEXT_MCP") == "1":
    if shutil.which("codebase-memory-mcp"):
        servers["codebase-memory-mcp"] = {"command": "codebase-memory-mcp", "args": []}
    if shutil.which("token-optimizer-mcp"):
        servers["token-optimizer-mcp"] = {
            "command": "token-optimizer-mcp",
            "args": [],
        }

print(json.dumps({"mcpServers": servers}, indent=2))
PYJSON
}

build_template_json() {
  GENERATED_MCP_JSON="$MCP_JSON" python3 - <<'PYJSON'
import json
import os

payload = json.loads(os.environ["GENERATED_MCP_JSON"])
payload = {
    "__TEMPLATE_WARNING__": "This is a template file for reference only. DO NOT add secrets here. Use setup_ide_mcp.sh to regenerate active configs.",
    **payload,
}
print(json.dumps(payload, indent=2))
PYJSON
}

build_codex_toml() {
  GENERATED_MCP_JSON="$MCP_JSON" python3 - <<'PYTOML'
import json
import os

servers = json.loads(os.environ["GENERATED_MCP_JSON"])["mcpServers"]
lines = ["# Auto-generated by scripts/setup_ide_mcp.sh. Do not edit by hand.", ""]
for name, server in servers.items():
    lines.append(f"[mcp_servers.{name}]")
    if "command" in server:
        lines.append(f"command = {server['command']!r}")
    if "args" in server:
        args = ", ".join(repr(arg) for arg in server["args"])
        lines.append(f"args = [{args}]")
    if "url" in server:
        lines.append(f"url = {server['url']!r}")
    env = server.get("env", {})
    if env:
        lines.append("")
        lines.append(f"[mcp_servers.{name}.env]")
        for key, value in env.items():
            lines.append(f"{key} = {value!r}")
    lines.append("")
print("\n".join(lines))
PYTOML
}

sync_json_mcp_key() {
  local full_path="$1"
  GENERATED_MCP_JSON="$MCP_JSON" TARGET_JSON="$full_path" MODE="$MODE" python3 - <<'PYSYNC'
import json
import os
import sys
from pathlib import Path

path = Path(os.environ["TARGET_JSON"])
expected = json.loads(os.environ["GENERATED_MCP_JSON"])["mcpServers"]
mode = os.environ["MODE"]
if not path.exists():
    print(f"Check Failed: {path} does not exist.")
    sys.exit(1)
with path.open(encoding="utf-8") as handle:
    data = json.load(handle)
actual = data.get("mcpServers")
if mode == "check":
    if actual != expected:
        print(f"Check Failed: {path} has drifted mcpServers.")
        sys.exit(1)
else:
    data["mcpServers"] = expected
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"Synced mcpServers in {path}")
PYSYNC
}

sync_devcontainer_mcp_keys() {
  local full_path="$1"
  GENERATED_MCP_JSON="$MCP_JSON" TARGET_JSON="$full_path" MODE="$MODE" python3 - <<'PYSYNC'
import json
import os
import sys
from pathlib import Path

path = Path(os.environ["TARGET_JSON"])
expected = json.loads(os.environ["GENERATED_MCP_JSON"])["mcpServers"]
mode = os.environ["MODE"]
with path.open(encoding="utf-8") as handle:
    data = json.load(handle)
changed = False
for customization in data.get("customizations", {}).values():
    settings = customization.get("settings") if isinstance(customization, dict) else None
    if isinstance(settings, dict) and "mcpServers" in settings:
        if settings["mcpServers"] != expected:
            if mode == "check":
                print(f"Check Failed: {path} has drifted customization mcpServers.")
                sys.exit(1)
            settings["mcpServers"] = expected
            changed = True
if mode != "check" and changed:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"Synced customization mcpServers in {path}")
PYSYNC
}

MCP_JSON="$(build_json)"
TEMPLATE_JSON="$(build_template_json)"
CODEX_TOML="$(build_codex_toml)"

if [ "$MODE" = "print" ]; then
  printf '%s\n' "$MCP_JSON"
  exit 0
fi

process_file() {
  local full_path="$1"
  local content="$2"
  if [ "$MODE" = "check" ]; then
    if [ ! -f "$full_path" ]; then
      echo "Check Failed: $full_path does not exist."
      exit 1
    fi
    if ! printf '%s\n' "$content" | diff -q - "$full_path" >/dev/null 2>&1; then
      echo "Check Failed: $full_path differs from expected configuration."
      exit 1
    fi
  else
    mkdir -p "$(dirname "$full_path")"
    printf '%s\n' "$content" > "$full_path"
    echo "Created $full_path"
  fi
}

active_files=(
  "$PROJECT_ROOT/.cursor/mcp.json"
  "$PROJECT_ROOT/.vscode/cline_mcp_settings.json"
  "$PROJECT_ROOT/.vscode/roo_cline_mcp_settings.json"
  "$PROJECT_ROOT/.windsurf/mcp.json"
  "$PROJECT_ROOT/.gemini/mcp.json"
  "$PROJECT_ROOT/.gemini/mcp-configs/mcp-servers.json"
  "$PROJECT_ROOT/.mcp.json"
  "$PROJECT_ROOT/mcp.json"
  "$PROJECT_ROOT/.agents/mcp.json"
)

for target in "${active_files[@]}"; do
  process_file "$target" "$MCP_JSON"
done

process_file "$PROJECT_ROOT/.claude/mcp-configs/mcp-servers.json" "$TEMPLATE_JSON"
process_file "$PROJECT_ROOT/.codex/config.toml" "$CODEX_TOML"
sync_json_mcp_key "$PROJECT_ROOT/.vscode/settings.json"
sync_devcontainer_mcp_keys "$PROJECT_ROOT/.devcontainer/devcontainer.json"

if [ "$MODE" = "check" ]; then
  echo "MCP Configurations check passed."
else
  echo "MCP Configurations generated successfully across all IDEs."
fi
